version: "3.7"

services:
  go-inventory:
    container_name: inventory-app
    build: .
    ports:
      - 3000:8080
    depends_on:
      - mysql
    networks:
      - book-app
    environment:
      GO_ENVIRONMENT: production
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: secret
      DB_NAME: inventory

  mysql:
    container_name: mysql-db-test
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: inventory
    networks:
      - book-app

volumes:
  mysql-data:

networks:
  book-app:
    driver: bridge