version: "3.7"

services:
  mysql:
    container_name: mysql-test
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: inventory
    networks:
      - inventory-net

  go-inventory:
    container_name: inventory-app
    build: .
    ports:
      - 3000:8080
    restart: on-failure
    depends_on:
      - mysql
    # links:
      # - "mysql:database"
    networks:
      - inventory-net
    environment:
      GO_ENVIRONMENT: production

volumes:
  mysql-data:

networks:
  inventory-net:
    driver: bridge